### ISSUE TITLE
httpcheck must be explicitly disabled

### ISSUE THREAD

**Issue by mtb-xt** [robertdebock/ansible-role-haproxy#10]
## Describe the bug

Hello good sir! I'm configuring my backends in tcp mode, and I have to explicitly set
`httpcheck: no`
Otherwise, the template explodes with:
```
TASK [robertdebock.haproxy : configure software] *********************************************************************************************
task path: /home/hawara/.ansible/roles/robertdebock.haproxy/tasks/main.yml:26
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'httpcheck'
fatal: [sentinel.home.hawara.nz]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'httpcheck'"}
```

## Playbook

```yaml
- name: Configure HA control plane
  hosts: control-plane
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.sysctl
      sysctl_items:
        - name: net.ipv4.ip_nonlocal_bind
          value: 1
    - role: robertdebock.keepalived
    - role: robertdebock.haproxy
      haproxy_frontends:
        - name: kubeAPI
          address: "172.21.34.230"
          port: 6443
          mode: tcp
          default_backend: kubeAPI_backend
        - name: konnectivity
          address: "172.21.34.230"
          port: 8132
          mode: tcp
          default_backend: konnectivity_backend
        - name: controllerJoinAPI
          address: "172.21.34.230"
          port: 9443
          mode: tcp
          default_backend: controllerJoinAPI_backend
      haproxy_backend_default_balance: roundrobin
      haproxy_backends:
        - name: kubeAPI_backend
          httpcheck: no
          balance: roundrobin
          servers: "{{ groups['control-plane'] }}"
          port: 6443
          options:
            - check
            - check-ssl
            - verify none
        - name: konnectivity_backend
          httpcheck: no
          balance: roundrobin
          servers: "{{ groups['control-plane'] }}"
          port: 8132
          options:
            - check
            - check-ssl
            - verify none
        - name: controllerJoinAPI_backend
          httpcheck: no
          balance: roundrobin
          servers: "{{ groups['control-plane'] }}"
          port: 9443
          options:
            - check
            - check-ssl
            - verify none
```

## Output

Show at least the error, possible related output, maybe just all the output.
![image](https://user-images.githubusercontent.com/11381295/189317062-14a7643a-34bd-4659-ab83-e271310e0cb1.png)

## Environment

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)
  Arch Linux
- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
  ansible [core 2.13.3]
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)
  Ubuntu 22.04.1 LTS

Please consider [sponsoring me](https://github.com/sponsors/robertdebock). :arrow_backward:  :heavy_check_mark:
