### ISSUE TITLE
"Listen" block support

### ISSUE THREAD

**Issue by heywood8** [robertdebock/ansible-role-haproxy#12]
## Proposed feature

Right now only "frontend" and "backend" blocks are supported. "listen" block needs to be added

## Rationale

"Listen" block is useful for tcp-proxies, e.g. MQTT
https://www.haproxy.com/documentation/hapee/latest/configuration/config-sections/listen/

**Comment by heywood8** [comment]
Could be done the same way as in haproxy_frontends, haproxy_backends.
Example for inventory:

```
haproxy_listens:
  - name: mqtt-main-1883
    mode: tcp
    address: "*"
    listen_port: 1883
    httpcheck: no
    servers:
      - name: mqtt-0
        address: 10.0.0.100
      - name: mqtt-1
        address: 10.0.0.101
    port: 1883
    options:
      - maxconn 100000 check port 1883
```
