### ISSUE TITLE
Enable health check

### ISSUE THREAD

**Issue by vmaillot** [robertdebock/ansible-role-haproxy#8]
## Proposed feature

At the moment we cannot enable health check like described in [here](https://www.haproxy.com/blog/how-to-enable-health-checks-in-haproxy). We would need to be able to do this:

```
backend api
  option httpchk
  http-check send meth GET  uri /healthz
  http-check expect status 200
  server server1 192.168.50.2:6443 check
  server server2 192.168.50.3:6443 check
  server server3 192.168.50.4:6443 check
backend ingress-http
  option httpchk
  http-check send meth HEAD  uri /
  http-check expect status 404 # not sure about this tho
  server server1 192.168.50.2:30080 check
  server server2 192.168.50.3:30080 check
  server server3 192.168.50.4:30080 check
```

## Rationale

To prepare SLA phase for a customer we would need this feature.

## Additional context

Thanks a lot for your consideration and help!

**Comment by robertdebock** [comment]
I've got this variable:

```yaml
      haproxy_backends:
        - name: backend
          httpcheck: yes
          # You can tell how the health check must be done.
          http_check:
            send:
              method: GET
              uri: /healthz
            expect: status 200
          balance: roundrobin
          # You can refer to hosts in an Ansible group.
          # The `ansible_default_ipv4` will be used as an address to connect to.
          servers: "{{ groups['all'] }}"
          port: 8080
          options:
            - check
```

To create this configuration:

```text
backend backend
    option httpchk
    http-check send meth GET uri /healthz
    http-check expect status 200
    balance roundrobin
    mode http
    server haproxy-fedora-latest 172.17.0.9:8080 check
```

I'll push and let CI test.
